# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='finalDestination',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='originalURL',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
