# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-04 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0002_auto_20160803_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='finalDestination',
            field=models.URLField(max_length=300, null=models.URLField(max_length=300, null=True)),
        ),
        migrations.AlterField(
            model_name='url',
            name='originalURL',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='statusCode',
            field=models.CharField(default=b'200', max_length=3),
        ),
    ]
